name: Commit
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - run: go mod tidy
      - run: go mod download
      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  setup:
    name: setup
    needs: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/app/vendor
            ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod vendor

  build:
    name: build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/app/vendor
            ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go vet ./...
      - run: go build -mod vendor -o cmd/main -ldflags '-linkmode external -w -extldflags "-static"' cmd/main.go
      - name: store built artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-poc-bin
          path: cmd/main

  integration-test:
    name: integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/app/vendor
            ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: docker compose up -d
      - run: go test ./tests/...
